-- PENDING_PAYMENT order state + CANCELLED checkout session state

ALTER TABLE `checkout_sessions`
  MODIFY COLUMN `status` ENUM('ACTIVE', 'CHECKING_OUT', 'COMPLETED', 'FAILED', 'EXPIRED', 'CANCELLED') NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `orders`
  MODIFY COLUMN `status` ENUM(
    'PENDING_PAYMENT',
    'PLACED',
    'PAYMENT_CONFIRMED',
    'PROCESSING',
    'SHIPPED',
    'OUT_FOR_DELIVERY',
    'DELIVERED',
    'CANCELLED',
    'RETURNED'
  ) NOT NULL DEFAULT 'PLACED';
