include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    avoid_redundant_argument_values: true
    unnecessary_parenthesis: true
    directives_ordering: true
